title: Zend een signaal in Scratch
hero_image: images/banner.png
description: Leer hoe je een bericht kunt zenden waarop verschillende sprites kunnen reageren
theme: red
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
interests: ""
technologies: "scratch"
site_areas:
steps:
  - title: Inleiding
