---
title: Zend een signaal in Scratch
hero_image: images / banner.png
description: Leer hoe je een bericht kunt sturen waarop verschillende sprites kunnen reageren
theme: rood
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: maker, ontwerp-0, programmeren-0, phys-comp-0, productie-0, community-0
interests: ""
technologies: "scratch"
site_areas: ""
steps:
  - 
    title: Inleiding
