---
title: Phát một tin nhắn trong Scratch
hero_image: images / banner.png
description: Tìm hiểu cách phát một tin nhắn có thể được tác động theo các họa tiết khác nhau
theme: đỏ
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: tác giả, thiết kế-0, lập trình-0, phys-comp-0, sản xuất-0, cộng đồng-0
interests: ""
technologies: "vết trầy"
site_areas:
steps:
  - 
    title: Giới thiệu
