---
title: Trasmetti un messaggio in Scratch
hero_image: images / banner.png
description: Impara come trasmettere un messaggio che può essere interpretato da diversi sprite
theme: rosso
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: creatore, design-0, programmazione-0, compatta-0, fabbricazione-0, comunità-0
interests: ""
technologies: "graffiare"
site_areas: ""
steps:
  - 
    title: introduzione
