---
title: 在 Scratch 中广播消息
hero_image: images/banner.png
description: 学习如何广播一个可以由不同精灵执行的消息
theme: 红色
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: 创建者, 设计-0, 编程-0, 物理组装-0, 制造-0, 社区-0
interests: ""
technologies: "scratch"
site_areas:
steps:
  - 
    title: 介绍
