---
title: Lähettää viesti tyhjästä
hero_image: Kuvien / banner.png
description: Opi lähettämään viesti, jonka eri sprites voi toimia
theme: punainen
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: luoja, design-0, ohjelmointi-0, phys-comp-0, valmistus-0, yhteisö-0
interests: ""
technologies: "naarmu"
site_areas: ""
steps:
  - 
    title: esittely
