---
title: Darlledwch neges yn Scratch
hero_image: images/banner.png
description: Dysgwch sut i ddarlledu neges y gall cipluniau eraill weithredu arni
theme: red
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
interests: ""
technologies: "scratch"
site_areas:
steps:
  - 
    title: Cyflwyniad
