---
title: Darlledwch neges yn Scratch
hero_image: delweddau / banner.png
description: Dysgwch sut i ddarlledu neges y gall sprites gwahanol ei weithredu arno
theme: Coch
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: crewr, dylunio-0, programming-0, phys-comp-0, manufacture-0, community-0
interests: ""
technologies: "crafu"
site_areas: ""
steps:
  - 
    title: Cyflwyniad
