---
title: Difuzarea un mesaj în Scratch
hero_image: images / banner.png
description: Învățați cum să difuzați un mesaj în funcție de care pot acționa diferite personaje
theme: roșu
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: creator, design-0, programare-0, fiz-comp-0, fabricare-0, comunitate-0
interests: ""
technologies: "zgârietură"
site_areas: ""
steps:
  - 
    title: Introducere
