---
title: Transmiteți un mesaj în Scratch
hero_image: images/banner.png
description: Învățați cum să transmiteti un mesaj în funcție de care pot acționa diferite personaje
theme: red
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
interests: ""
technologies: "scratch"
site_areas:
steps:
  - title: Introducere
