---
title: Transmita uma mensagem no Scratch
hero_image: images / banner.png
description: Saiba como transmitir uma mensagem que pode ser realizada por diferentes sprites
theme: vermelho
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: criador, design-0, programação-0, phys-comp-0, manufacture-0, community-0
interests: ""
technologies: "coçar, arranhão"
site_areas:
steps:
  - 
    title: Introdução
