---
title: Sporočite sporočilo v Scratchu
hero_image: images / banner.png
description: Naučite se, kako oddati sporočilo, na katerega se lahko odzovejo različni spriti
theme: rdeča
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: ustvarjalec, design-0, programiranje-0, fiz-comp-0, izdelava-0, skupnost-0
interests: ""
technologies: "praska"
site_areas: ""
steps:
  - 
    title: Uvod
