---
title: Üzenet átadása a Scratchban
hero_image: images / banner.png
description: Ismerje meg, miként közvetíthet egy üzenetet, amelyet különböző spritesek végezhetnek
theme: piros
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: alkotó, design-0, programozás-0, fiz-comp-0, gyártás-0, community-0
interests: ""
technologies: "karcolás"
site_areas:
steps:
  - 
    title: Bevezetés
