---
title: 從頭開始廣播信息
hero_image: 圖片/ banner.png
description: 了解如何廣播可以由不同子畫面執行的消息
theme: 紅
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: 創作者，設計-0，編程-0，物理comp-0，製造-0，社區-0
interests: ""
technologies: "刮"
site_areas: ""
steps:
  - 
    title: 介紹
