---
title: Emisja wiadomości w Scratch
hero_image: images / banner.png
description: Dowiedz się, jak nadać komunikat, który może być obsługiwany przez różne sprite'y
theme: czerwony
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: twórca, design-0, programowanie-0, phys-comp-0, production-0, community-0
interests: ""
technologies: "zadraśnięcie"
site_areas: ""
steps:
  - 
    title: Wprowadzenie
