---
title: Sänd ett meddelande i Scratch
hero_image: images / banner.png
description: Lär dig hur du sänder ett meddelande som kan hanteras av olika sprites
theme: röd
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: skapare, design-0, programmering-0, phys-comp-0, tillverkning-0, community-0
interests: ""
technologies: "repa"
site_areas:
steps:
  - 
    title: Introduktion
