---
title: Μετάδωσε ένα μήνυμα στο Scratch
hero_image: images/banner.png
description: Μάθε πώς να εκπέμπεις ένα μήνυμα το οποίο μπορεί να επηρεάσει διαφορετικά αντικείμενα
theme: κόκκινο
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: δημιουργός, σχεδιασμός-0, προγραμματισμός-0, phys-comp-0, κατασκευή-0, κοινότητα-0
interests: ""
technologies: "scratch"
site_areas: ""
steps:
  - 
    title: Εισαγωγή
