---
title: Inviare un messaggio in Scratch
hero_image: images/banner.png
description: Impara a inviare un messaggio che può essere ricevuto e interpretato da diversi sprite
theme: red
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
interests: ""
technologies: "scratch"
site_areas: ""
steps:
  - 
    title: Introduzione
