---
title: Scratch'da bir mesaj yayınla
hero_image: images / banner.png
description: Farklı spritelarla hareket edebilecek bir mesajı nasıl yayınlayacağınızı öğrenin.
theme: kırmızı
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: creator, design-0, programlama-0, fiz-comp-0, production-0, topluluk-0
interests: ""
technologies: "çizik"
site_areas:
steps:
  - 
    title: Giriş
